[package]
name = "cargo-compare"
version = "0.1.0"
authors = ["Rain <rain1@calibra.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.28"
cargo = "0.44.0"
diffus = "0.9.1"
guppy = { path = "../../guppy" }
guppy-cmdlib = { path = "../../guppy-cmdlib" }
structopt = "0.3"
