[package]
name = "guppy"
version = "0.1.6"
description = "Track and query Cargo dependency graphs."
documentation = "https://docs.rs/guppy"
repository = "https://github.com/calibra/cargo-guppy"
authors = ["Rain <rain1@calibra.com>", "Brandon Williams <bmwill@calibra.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cargo", "dependencies", "reverse-dependencies", "dependency-graph", "graphviz"]
categories = ["config", "data-structures", "development-tools", "parser-implementations"]
edition = "2018"
exclude = [
    # Skip over test fixtures since they're pretty large (several MB).
    "fixtures/*",
    # Readme template that doesn't need to be included.
    "README.tpl",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
all-features = true

[badges]
circle-ci = { repository = "calibra/cargo-guppy", branch = "master"}
maintenance = { status = "actively-developed" }

[dependencies]
cargo_metadata = "0.9"
derivative = "2"
fixedbitset = { version = "0.2.0", default-features = false }
nested = "0.1.1"
indexmap = "1.3.1"
once_cell = "1.2.0"
petgraph = { version = "0.5", default-features = false }
proptest = { version = "0.9", optional = true }
proptest-derive = { version = "0.1.2", optional = true }
semver = "0.9.0"
semver-parser = "0.9.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"

[dev-dependencies]
assert_matches = "1.3.0"
pretty_assertions = "0.6.1"

[features]
proptest09 = ["proptest", "proptest-derive"]
